name: Flutter Checks

on:
  push:
    branches:
      - main
      - version-11
  pull_request:
    branches:
      - main

jobs:
  flutter-checks:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          cache: true

      - name: Install dependencies
        run: flutter pub get

      - name: Analyze code
        run: "flutter analyze --no-fatal-infos"

      - name: Run tests
        run: flutter test